tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-container-highest": "#e1e3e2",
                "surface-tint": "#3b6756",
                "surface-bright": "#f8faf9",
                "error": "#ba1a1a",
                "surface-container": "#edeeed",
                "primary-container": "#0f3d2e",
                "outline-variant": "#c0c8c3",
                "outline": "#717974",
                "secondary-fixed": "#d3e7dd",
                "surface": "#f8faf9",
                "surface-dim": "#d9dad9",
                "surface-variant": "#e1e3e2",
                "on-background": "#191c1c",
                "on-tertiary-fixed-variant": "#6a3a20",
                "inverse-surface": "#2e3131",
                "on-secondary-fixed": "#0e1f19",
                "surface-container-high": "#e7e8e7",
                "on-tertiary-fixed": "#341100",
                "secondary-fixed-dim": "#b7cbc1",
                "on-tertiary-container": "#d0906f",
                "on-secondary-fixed-variant": "#394b43",
                "tertiary": "#3b1601",
                "on-surface": "#191c1c",
                "on-tertiary": "#ffffff",
                "on-secondary-container": "#54675f",
                "tertiary-fixed": "#ffdbcb",
                "inverse-primary": "#a2d1bb",
                "surface-container-lowest": "#ffffff",
                "on-surface-variant": "#414944",
                "tertiary-container": "#562a11",
                "primary-fixed-dim": "#a2d1bb",
                "primary-fixed": "#beedd7",
                "on-error": "#ffffff",
                "secondary-container": "#d0e4da",
                "on-primary-container": "#7ba894",
                "background": "#f8faf9",
                "on-secondary": "#ffffff",
                "on-primary-fixed-variant": "#234f3f",
                "on-error-container": "#93000a",
                "tertiary-fixed-dim": "#fdb793",
                "primary": "#00261a",
                "error-container": "#ffdad6",
                "on-primary-fixed": "#002116",
                "on-primary": "#ffffff",
                "secondary": "#50625a",
                "inverse-on-surface": "#f0f1f0",
                "surface-container-low": "#f3f4f3"
            },
            fontFamily: {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
        },
    },
};
